### ISSUE TITLE
Add suitable readme !

### ISSUE THREAD

**Issue by FlameFractal** [FlameFractal/imad-2016-app#6]

**Comment by anantajitjg** [comment]
@FlameFractal , in your readme,
change,
Live at : [Heroku](imad-blog.herokuapp.com) & [Hasura-IMAD](flamefractal.imad.hasura-app.io)
to,
`Live at : [Heroku](http://imad-blog.herokuapp.com) & [Hasura-IMAD](http://flamefractal.imad.hasura-app.io)`

**see the difference** (_click each links_)**?**

**Comment by FlameFractal** [comment]
I did change that on the blog webapp but missed the protocol here.
Thanks for noticing ✌️ 

Edit:
I'm rendering readme on the webapp straight from github now, so they can always be in sync! Thanks. @anantajitjg
